[package]
name = "sillyx"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
fastcgi-client = "0.9.0"
tracing = "0.1"
tracing-subscriber = "0.3"
salvo = "0.75"
clap = "4.5"
lazy_static = "1.5.0"
